authorName: Allyson Jeffredo
#url: https://www.allysonjeffredo.com
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
image: assets/images/preview-3f86b4dabb84405e31c11360eb2ed772-750.png
markdown: kramdown
destination: dist
source: root/jekyll
plugins:
    - jemoji
    - jekyll-sitemap
include:
    - _pages
timezone: America/Los_Angeles
