authorName: Allyson Jeffredo
#url: https://www.allysonjeffredo.com
favicon: assets/images/favicon.ico
title: Allyson Jeffredo
email: a.jeffredo2@gmail.com
type: website
description: Hello! I'm Allyson. Poet, writer, educator.
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
image: assets/images/preview.png
facebookAppId: 397283870738655
twitterUrl: https://twitter.com/allyj0_0
twitterUsername: allyj0_0
facebookUrl: https://www.facebook.com/allyson.jeffredo
instagramUrl: https://www.instagram.com/allyj0_0
googleAnalyticsId: UA-116050053-1
markdown: kramdown
destination: dist
source: root/jekyll
plugins:
    - jemoji
    - jekyll-sitemap
include:
    - _pages
timezone: America/Los_Angeles
