authorName: Allyson Jeffredo
url: https://www.allysonjeffredo.com/
favicon: assets/img/favicon.ico
title: Allyson Jeffredo
email: a.jeffredo2@gmail.com
ogTitle: Hello! I'm Allyson
ogType: website
ogDescription: I'm Allyson. Poet, writer, educator.
ogImage: assets/img/preview.png
ogUrl: https://www.allysonjeffredo.com/
facebookAppId: 397283870738655
twitterUrl: https://twitter.com/allyj0_0
twitterUsername: allyj0_0
facebookUrl: https://www.facebook.com/allyson.jeffredo
instagramUrl: https://www.instagram.com/allyj0_0
googleAnalyticsId: UA-116050053-1
markdown: kramdown
plugins:
  - jemoji
include: [_pages]
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - package-lock.json
  - src
timezone: America/Los_Angeles